# Site settings
title: Les Éditions AOJB
email: your-email@domain.com
description: >
  je suis AOJB 
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: ""
image: utopie.jpg
url: "https://amzn.to/2JgHznh"

# Collections
#collections:
#  books:
#    output: false

sass:
  style: compressed
